LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY SHIFT_LEFT2 IS 
    PORT (
        IN_SIGNAL : IN STD_LOGIC_VECTOR(15 DOWNTO 0);
        OUT_SIGNAL : OUT STD_LOGIC_VECTOR(15 DOWNTO 0)
    );
END SHIFT_LEFT2;

ARCHITECTURE Behavior OF SHIFT_LEFT2 IS

SIGNAL AUX1 : STD_LOGIC; 

BEGIN
    
    OUT_SIGNAL <= IN_SIGNAL(13 downto 0) & "00";

END Behavior;
